resource_types:
- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: vhobby-project
  type: git
  source:
    uri:  ((project_src_uri))
    branch: ((project_src_branch))
    private_key: ((project_src_private_key))

jobs:
- name: vhobby-release-pipeline-test
  plan:
  - get: vhobby-project
    trigger: true
  - task: release-to-test
    file: vhobby-project/concourse/tasks/deployTest.yml
    input_mapping:
        project_src: vhobby-project
