version: '2'
services:
  web:
    links:
     - "redis-master"
     - "redis-slave"
    build:
        context: "./webapp"
        dockerfile: Web-Dockerfile
    ports:
     - "80:80"
  redis-master:
    build:
        context: "./data"
        dockerfile: Master-Dockerfile
  redis-slave:
    build:
        context: "./data"
        dockerfile: Slave-Dockerfile
