---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: fcarta29/vmware
    tag: '1.0'

inputs:
- name: project_src
- name: terraform_state
- name: terraform_vars

run:
  dir: project_src
  args:
    - prod
  path: concourse/scripts/deploy.sh
