---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: fcarta29/vmware2
    tag: '1.0'

inputs:
- name: project_src

run:
  dir: project_src
  args:
    - 10.40.207.183
    - vhobby
    - 0
  path: concourse/scripts/test.sh
